site_name: CD-MOJ

theme:
  name: material
  logo: assets/icons/computer_white.png
  language: 'pt'

extra_css:
  - stylesheets/extra.css

pages:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Apresentações: apresentacoes.md
  #sempre a ultima
  - Atas:
      - 30/09/2020: atas/reuniao-30-09-2020.md
