site_name: CD-MOJ

theme:
  name: material
  logo: assets/icons/computer_white.png
  language: 'pt'

extra_css:
  - stylesheets/extra.css

pages:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Perfil de usuário:
    - Personas: personas.md
  - Apresentações: apresentacoes.md
