site_name: CD-MOJ

theme:
  name: material
  logo: assets/icons/computer_white.png
  language: 'pt'

extra_css:
  - stylesheets/extra.css

pages:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Perfil de usuário:
    - Personas: personas.md
  - Análise de tarefas:
    - Análise Hierárquica de tarefas: analise_tarefas.md
  - Apresentações: apresentacoes.md
  #sempre a ultima
  - Atas:
      - 30/09/2020: atas/reuniao-30-09-2020.md
