site_name: CD-MOJ

theme:
  name: material
  logo: assets/icons/computer_white.png
  language: 'pt'

extra_css:
  - stylesheets/extra.css

pages:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Análise de requisitos:
    - Perfil de usuário:
      - Personas: analise_requisitos/personas.md
    - Análise de tarefas:
      - Análise Hierárquica de tarefas: analise_requisitos/analise_tarefas/hta.md
      - GOMS: analise_requisitos/analise_tarefas/goms.md
    - Características da plataforma: analise_requisitos/caracteristicas.md
    - Princípios e diretrizes do projeto: analise_requisitos/principios.md
    - Metas de usabilidade: analise_requisitos/metas_de_usabilidade.md
    - Guia de estilo: analise_requisitos/guia_estilo.md
  - Design, avaliação e desenvolvimento:
    - Reengenharia do trabalho: DeAD/reestruturacao_tarefas.md
  - Apresentações: apresentacoes.md
  #sempre a ultima
  - Atas:
      - 30/09/2020: atas/reuniao-30-09-2020.md
      - 19/10/2020: atas/reuniao-19-10-2020.md
